TEMPLATES = [
    "Non-free 2D art",
    "Non-free 3D art",
    "Non-free aircraft image",
    "Non-free album cover",
    "Non-free audio sample",
    "Non-free AUSPIC",
    "Non-free Australian Crown copyright",
    "Non-free biog-pic",
    "Non-free board game cover",
    "Non-free book cover",
    "Non-free Canadian Crown Copyright",
    "Non-free card",
    "Non-free character",
    "Non-free comic",
    "Non-free computer icon",
    "Non-free Crown copyright",
    "Non-free currency",
    "Non-free currency-AU-Coin",
    "Non-free currency-AU-Note",
    "Non-free currency-EU coin national",
    "Non-free currency-New Zealand",
    "Non-free currency-UK",
    "Non-free currency-UK-obsolete",
    "Non-free Denver Public Library image",
    "Non-free destroyed architecture",
    "Non-free ESA media",
    "Non-free fair use",
    "Non-free film poster",
    "Non-free film screenshot",
    "Non-free Finnish Defence Forces",
    "Non-free graffiti",
    "Non-free historic image",
    "Non-free Hong Kong Government",
    "Non-free logo",
    "Non-free magazine cover",
    "Non-free mascot",
    "Non-free Mozilla logo",
    "Non-free music video screenshot",
    "Non-free music interface",
    "Non-free NASA",
    "Non-free New Zealand Crown Copyright",
    "Non-free newspaper image",
    "Non-free no treaty",
    "Non-free Commonwealth Games media",
    "Non-free FIFA media",
    "Non-free in US",
    "Non-free license plate",
    "Not-PD-US-URAA",
    "Non-free Old-25",
    "Non-free Old-30",
    "Non-free Old-50",
    "Non-free Old-60",
    "Non-free Old-70",
    "Non-free Old-75",
    "Non-free Old-80",
    "Non-free Old-auto",
    "Non-free Olympics media",
    "Non-free Otto Perry image",
    "Non-free Parliamentary copyright",
    "Non-free Pan American Games media",
    "Non-free Paralympics logo",
    "Non-free Paralympics media",
    "Permission from license selector",
    "Non-free Philippines government",
    "Non-free political poster",
    "Possibly non-free in US",
    "Non-free poster",
    "Non-free product cover",
    "Non-free promotional",
    "Non-free proposed architecture",
    "Non-free school logo",
    "Non-free Scout logo",
    "Non-free seal",
    "Non-free sheet music",
    "Non-free software cover",
    "Non-free Microsoft screenshot",
    "Non-free software screenshot",
    "Non-free speech",
    "Non-free sports uniform",
    "Non-free stamp",
    "Non-free stamp of Canada",
    "Non-free symbol",
    "Non-free television screenshot",
    "Non-free title-card",
    "Non-free USGov-IEEPA sanctions",
    "Non-free USGov-USPS stamp",
    "Non-free USStateGov",
    "Non-free vehicle image",
    "Non-free video cover",
    "Non-free video game cover",
    "Non-free video game screenshot",
    "Non-free video sample",
    "Non-free video screenshot",
    "Non-free vodcast screenshot",
    "Non-free watercraft image",
    "Non-free web screenshot",
    "Non-free file with no commercial use license",
    "Non-free with NC and ND",
    "Non-free file with no derivative works license",
    "Non-free with permission",
    "Non-free media data",
    "Non-free media rationale",
    "Non-free use rationale album cover",
    "Album rationale",
    "Non-free audio data",
    "Non-free use rationale audio sample",
    "Backmasked-b",
    "Backmasked-f",
    "Non-free use rationale biog",
    "Non-free use rationale book cover",
    "Book rationale",
    "Comic cover rationale",
    "Cover rationale",
    "Film poster rationale",
    "Game rationale",
    "Icon rationale",
    "Images with no fair use rationale subcat starter",
    "Label rationale",
    "Non-free use rationale logo",
    "Logo rationale",
    "Magazine rationale",
    "Manga rationale",
    "Non-free use rationale currency",
    "Newspaper rationale",
    "Non-free use rationale",
    "Non-free use rationale product cover",
    "Non-free use rationale poster",
    "Rationale",
    "School rationale",
    "Non-free use rationale serial publication",
    "Non-free use rationale software cover",
    "Non-free use rationale software screenshot",
    "Symbol rationale",
    "Non-free use rationale title-card",
    "Non-free use rationale video cover",
    "Non-free use rationale video game cover",
    "Non-free use rationale video game screenshot",
    "Website screenshot rationale"
]
