// Generated by Cypress Author — 2026-07-10
//
// E2E tests for authentication flows in the WikiFile-Transfer app.
// Validates login/logout button visibility, user avatar display,
// and navigation gating based on auth state.

describe('Authentication', () => {
  describe('when logged out', () => {
    beforeEach(() => {
      // Default stubs already set the user as logged out
      cy.visit('/#/');
    });

    it('shows "Login to upload images" button → no "Start uploading"', () => {
      cy.contains('button', 'Login to upload images').should('be.visible');
      cy.contains('button', 'Start uploading').should('not.exist');
    });

    it('header shows Login button without avatar or Logout', () => {
      cy.contains('button', 'Login').should('be.visible');
      cy.contains('button', 'Logout').should('not.exist');
      // Avatar should not be rendered for logged-out users
      cy.get('.MuiAvatar-root').should('not.exist');
    });
  });

  describe('when logged in', () => {
    beforeEach(() => {
      cy.login('TestUser');
      cy.visit('/#/');
    });

    it('shows "Start uploading" button → no "Login to upload images"', () => {
      cy.contains('button', 'Start uploading').should('be.visible');
      cy.contains('button', 'Login to upload images').should('not.exist');
    });

    it('header shows user avatar with initials and Logout button', () => {
      // Avatar should display the first letter of the username
      cy.get('.MuiAvatar-root').should('be.visible').and('contain.text', 'T');
      cy.contains('button', 'Logout').should('be.visible');
      cy.contains('button', 'Login').should('not.exist');
    });

    it('"Start uploading" button navigates to the upload page', () => {
      cy.contains('button', 'Start uploading').click();
      // Verify we're on the upload page by checking for the stepper
      cy.contains('Enter Source URL').should('be.visible');
    });
  });
});
