// Generated by Cypress Author — 2026-07-10
//
// E2E tests for internationalization (i18n) in WikiFile-Transfer.
// Validates default language, language selector visibility,
// and that switching language persists via the backend API.
//
// NOTE: MUI Select renders its dropdown inside a Modal with a
// MuiBackdrop-root overlay. Cypress considers the listbox "covered"
// by the backdrop. We use { force: true } on the option click to
// bypass this, or target the option elements directly.

describe('Internationalization (i18n)', () => {
  beforeEach(() => {
    cy.stubSaveUserLanguage();
  });

  it('default language is English → site title shows "Wikifile-transfer"', () => {
    cy.visit('/#/');
    cy.contains('Wikifile-transfer').should('be.visible');
    cy.contains('Welcome to the Wikifile-transfer tool page!').should('be.visible');
  });

  it('language selector in header is visible and contains options', () => {
    cy.visit('/#/');

    // The language selector is an MUI Select in the header AppBar
    cy.get('.MuiAppBar-root .MuiSelect-select').should('be.visible');
  });

  it('switching language calls POST /api/user_language with the selected language code', () => {
    cy.visit('/#/');

    // Open the language selector dropdown
    cy.get('.MuiAppBar-root .MuiSelect-select').click();

    // MUI renders the dropdown options inside a portal at document body level.
    // The options have role="option". Use { force: true } to bypass the
    // MuiBackdrop overlay that Cypress considers "covering" the element.
    cy.get('[role="option"]')
      .not(':contains("English")')
      .first()
      .click({ force: true });

    // Verify the POST was sent to persist the language choice
    cy.wait('@saveUserLanguage')
      .its('request.body')
      .should('have.property', 'user_language');
  });
});
