// Generated by Cypress Author — 2026-07-10
//
// E2E tests for page routing and navigation across the WikiFile-Transfer app.
// Validates that all routes render correct content and that the header
// conditionally shows nav tabs based on authentication state.

describe('Navigation', () => {
  describe('Page routing', () => {
    it('home page loads and shows welcome text', () => {
      cy.visit('/#/');
      cy.contains('Welcome to the Wikifile-transfer tool page!').should('be.visible');
    });

    it('about page loads and shows heading', () => {
      cy.visit('/#/about');
      cy.contains('About the tool').should('be.visible');
    });

    it('invalid route shows 404 page', () => {
      cy.visit('/#/nonexistent');
      cy.contains('404').should('be.visible');
      cy.contains('Oops! Page Not Found').should('be.visible');
    });

    it('404 page "Back to home" button navigates to home', () => {
      cy.visit('/#/nonexistent');
      cy.contains('button', 'Back to home').click();
      cy.contains('Welcome to the Wikifile-transfer tool page!').should('be.visible');
    });
  });

  describe('Header navigation tabs', () => {
    it('logged-out user sees only Home and About tabs', () => {
      cy.visit('/#/');

      // Home and About tabs should be visible
      cy.contains('[role="tab"]', 'Home').should('be.visible');
      cy.contains('[role="tab"]', 'About').should('be.visible');

      // Upload and Preference tabs should NOT exist
      cy.contains('[role="tab"]', 'Upload').should('not.exist');
      cy.contains('[role="tab"]', 'Preference').should('not.exist');
    });

    it('logged-in user sees all four tabs', () => {
      cy.login('TestUser');
      cy.visit('/#/');

      cy.contains('[role="tab"]', 'Home').should('be.visible');
      cy.contains('[role="tab"]', 'Upload').should('be.visible');
      cy.contains('[role="tab"]', 'Preference').should('be.visible');
      cy.contains('[role="tab"]', 'About').should('be.visible');
    });

    it('clicking site title navigates to home page', () => {
      cy.visit('/#/about');
      cy.contains('About the tool').should('be.visible');

      // Click the site title link in the header
      cy.contains('a', 'Wikifile-transfer').click();
      cy.contains('Welcome to the Wikifile-transfer tool page!').should('be.visible');
    });
  });
});
