// Generated by Cypress Author — 2026-07-10
//
// E2E tests for the Preferences page in WikiFile-Transfer.
// Validates loading saved preferences, saving new ones, the skip-selection
// checkbox, and cancel navigation.
//
// NOTE: The header also renders an MUI Select (language dropdown) with
// role="combobox". We scope assertions to the preferences form area
// via the "My preferences" heading's parent container to avoid
// accidentally matching the header's combobox.

describe('Preferences', () => {
  beforeEach(() => {
    cy.login('TestUser');
    cy.stubPreferences();
    cy.stubSavePreferences();
    cy.stubSaveUserLanguage();
    cy.visit('/#/preferences');
  });

  it('displays "My preferences" heading', () => {
    cy.contains('My preferences').should('be.visible');
  });

  it('loads and displays saved project and language preferences', () => {
    // Scope to the form container (parent of the h4 heading) to avoid
    // picking up the header's language Select combobox.
    cy.contains('h4', 'My preferences').parent().within(() => {
      // First combobox inside the form = project dropdown
      cy.get('[role="combobox"]').first().should('contain.text', 'Wikipedia');

      // Second combobox inside the form = language dropdown
      cy.get('[role="combobox"]').eq(1).should('be.visible');
    });
  });

  it('Save button sends POST /api/preference → shows success toast', () => {
    cy.contains('button', 'Save').click();

    cy.wait('@savePreferences').its('request.body').should('deep.include', {
      project: 'wikipedia',
      lang: 'en',
    });

    // Success toast should appear
    cy.contains('Preferences saved successfully').should('be.visible');
  });

  it('Cancel button navigates back to home page', () => {
    cy.contains('button', 'Cancel').click();

    // Should be back on the home page
    cy.contains('Welcome to the Wikifile-transfer tool page!').should('be.visible');
  });

  it('skip upload selection checkbox is visible and toggleable', () => {
    // The checkbox should exist with its label
    cy.contains('Skip project and language selection during the upload step.')
      .should('be.visible');

    // Find the checkbox input and verify it starts unchecked (default stub)
    cy.get('input[type="checkbox"]').should('not.be.checked');

    // Toggle the checkbox
    cy.get('input[type="checkbox"]').check();
    cy.get('input[type="checkbox"]').should('be.checked');
  });
});
