// Generated by Cypress Author — 2026-07-10
//
// E2E tests for the full 4-step upload workflow in WikiFile-Transfer.
// Covers URL entry, project/language selection, filename validation,
// sync & async upload, template editing, result display, and the
// skip-selection preference shortcut.
//
// NOTE: `cy.get('input')` is avoided because the header's MUI language
// Select renders a hidden native <input class="MuiSelect-nativeInput">,
// causing "cy.type() can only be called on a single element". We use
// `input:not(.MuiSelect-nativeInput)` to target only visible TextFields.
//
// NOTE: The i18n key "next" is missing from en.json, so t("next")
// returns the raw key "next" (lowercase). Same for t("back") → "back".

describe('Upload Workflow', () => {
  const VALID_SOURCE_URL = 'https://en.wikipedia.org/wiki/File:Example.jpg';

  // Selector that targets MUI TextField inputs only, excluding the
  // hidden native input rendered by MUI Select in the header.
  const TEXT_INPUT = 'input:not(.MuiSelect-nativeInput)';

  beforeEach(() => {
    // Authenticate the user so the upload page is accessible
    cy.login('TestUser');
    cy.stubPreferences();
    cy.stubWikimediaFileCheck();
    cy.stubSaveUserLanguage();
  });

  describe('Step 1 — Enter Source URL', () => {
    beforeEach(() => {
      cy.visit('/#/upload');
    });

    it('displays the stepper with all 4 step labels and the source URL input', () => {
      // Verify all four step labels are visible in the stepper
      cy.contains('.MuiStepLabel-label', 'Enter Source URL').should('be.visible');
      cy.contains('.MuiStepLabel-label', 'Select Project & Language').should('be.visible');
      cy.contains('.MuiStepLabel-label', 'Name of Target File').should('be.visible');
      cy.contains('.MuiStepLabel-label', 'Add Template').should('be.visible');

      // Source URL input should be present
      cy.get(TEXT_INPUT).should('be.visible');
    });

    it('shows error toast when clicking Next with an empty URL', () => {
      // The button text is "next" (lowercase — key missing from en.json)
      cy.contains('button', 'next').click();
      // The toast should contain the validation error
      cy.contains('Please enter a valid source URL').should('be.visible');
    });

    it('advances to Step 2 after entering a valid source URL', () => {
      cy.get(TEXT_INPUT).type(VALID_SOURCE_URL);
      cy.contains('button', 'next').click();

      // Step 2 should show project and language dropdowns
      cy.contains('Select project').should('be.visible');
      cy.contains('Select language').should('be.visible');
    });
  });

  describe('Step 2 — Select Project & Language', () => {
    beforeEach(() => {
      cy.visit('/#/upload');
      // Navigate through Step 1
      cy.get(TEXT_INPUT).type(VALID_SOURCE_URL);
      cy.contains('button', 'next').click();
      // Wait for Step 2 to render
      cy.contains('Select project').should('be.visible');
    });

    it('project dropdown is pre-populated from preferences and language list updates', () => {
      // The project dropdown should reflect the stubbed preference ('wikipedia')
      // MUI Select renders the selected value inside the combobox element.
      // Skip the header's language selector (index 0) — page selectors start at index 1.
      cy.get('[role="combobox"]').eq(1).should('contain.text', 'Wikipedia');
    });

    it('advances to Step 3 with target filename auto-populated from URL', () => {
      cy.contains('button', 'next').click();

      // Step 3 should show the target file name input
      cy.contains('Name of the Target file').should('be.visible');
      // The filename 'Example' should be auto-extracted from the source URL
      cy.get(TEXT_INPUT).should('have.value', 'Example');
    });
  });

  describe('Step 3 — Upload to target wiki', () => {
    beforeEach(() => {
      cy.visit('/#/upload');
      // Navigate through Steps 1 → 2 → 3
      cy.get(TEXT_INPUT).type(VALID_SOURCE_URL);
      cy.contains('button', 'next').click();
      cy.contains('Select project').should('be.visible');
      cy.contains('button', 'next').click();
      cy.contains('Name of the Target file').should('be.visible');
    });

    it('sync upload success → advances to Step 4 with wikitext textarea', () => {
      // Stub the upload to succeed synchronously
      cy.stubUpload({
        success: true,
        data: {
          wikipage_url: 'https://en.wikipedia.org/wiki/File:Example.jpg',
          file_link: 'https://upload.wikimedia.org/wikipedia/en/a/a1/Example.jpg',
          source: VALID_SOURCE_URL,
        },
        errors: [],
      });
      cy.stubWikitext();

      cy.contains('button', 'Upload file to target wiki').click();

      // Step 4: template editing textarea should appear
      cy.get('textarea').should('be.visible');
      cy.contains('button', 'Finish without edit').should('be.visible');
      cy.contains('button', 'Finish with edit').should('be.visible');
    });

    it('upload failure → shows error toast', () => {
      cy.stubUpload({ success: false, data: {}, errors: ['Upload failed'] }, 500);

      cy.contains('button', 'Upload file to target wiki').click();

      cy.contains('An error occurred during upload').should('be.visible');
    });
  });

  describe('Step 4 — Add Template & Results', () => {
    // Helper: navigate all the way to Step 4
    beforeEach(() => {
      // Stub upload and wikitext for the journey
      cy.stubUpload({
        success: true,
        data: {
          wikipage_url: 'https://en.wikipedia.org/wiki/File:Example.jpg',
          file_link: 'https://upload.wikimedia.org/wikipedia/en/a/a1/Example.jpg',
          source: VALID_SOURCE_URL,
        },
        errors: [],
      });
      cy.stubWikitext('== Description ==\nSample wikitext');

      cy.visit('/#/upload');
      // Step 1
      cy.get(TEXT_INPUT).type(VALID_SOURCE_URL);
      cy.contains('button', 'next').click();
      // Step 2
      cy.contains('Select project').should('be.visible');
      cy.contains('button', 'next').click();
      // Step 3 → upload
      cy.contains('Name of the Target file').should('be.visible');
      cy.contains('button', 'Upload file to target wiki').click();
      // Wait for Step 4
      cy.get('textarea').should('be.visible');
    });

    it('"Finish without edit" → shows result page with wiki page link and home button', () => {
      cy.contains('button', 'Finish without edit').click();

      // Result page should display
      cy.contains('View Wiki Page').should('be.visible');
      cy.contains('Go Back to Home').should('be.visible');
    });

    it('"Finish with edit" → calls /api/edit_page and shows result page', () => {
      cy.stubEditPage(true);

      cy.contains('button', 'Finish with edit').click();
      cy.wait('@editPage');

      // Result page should display after edit
      cy.contains('View Wiki Page').should('be.visible');
      cy.contains('Go Back to Home').should('be.visible');
    });

    it('result page "Go Back to Home" button navigates to home', () => {
      cy.contains('button', 'Finish without edit').click();
      cy.contains('View Wiki Page').should('be.visible');

      cy.contains('button', 'Go Back to Home').click();
      cy.contains('Welcome to the Wikifile-transfer tool page!').should('be.visible');
    });
  });

  describe('Skip selection preference', () => {
    it('skips Step 2 when skip_upload_selection is true → jumps from Step 1 to Step 3', () => {
      // Override preferences to enable skip
      cy.stubPreferences({ skip_upload_selection: true });

      cy.visit('/#/upload');

      // Step 1: enter URL
      cy.get(TEXT_INPUT).type(VALID_SOURCE_URL);
      cy.contains('button', 'next').click();

      // Should jump directly to Step 3 (target file name), skipping Step 2
      cy.contains('Name of the Target file').should('be.visible');
      // Project/language dropdowns should NOT be visible
      cy.contains('Select project').should('not.exist');
    });
  });

  describe('Async upload with polling', () => {
    it('handles async upload → polls task status → shows result on SUCCESS', () => {
      // Stub upload to return 202 with a task ID (async)
      cy.intercept('POST', '**/api/upload', {
        statusCode: 202,
        body: { success: true, task_id: 'test-task-123' },
      }).as('uploadFile');

      // Stub task status to return SUCCESS
      cy.stubTaskStatus('test-task-123', {
        task_id: 'test-task-123',
        status: 'SUCCESS',
        result: {
          wikipage_url: 'https://en.wikipedia.org/wiki/File:Example.jpg',
          file_link: 'https://upload.wikimedia.org/wikipedia/en/a/a1/Example.jpg',
        },
      });
      cy.stubWikitext();

      cy.visit('/#/upload');
      // Navigate to Step 3
      cy.get(TEXT_INPUT).type(VALID_SOURCE_URL);
      cy.contains('button', 'next').click();
      cy.contains('Select project').should('be.visible');
      cy.contains('button', 'next').click();
      cy.contains('Name of the Target file').should('be.visible');

      // Trigger upload
      cy.contains('button', 'Upload file to target wiki').click();
      cy.wait('@uploadFile');

      // Wait for polling to complete and Step 4 to appear
      cy.wait('@getTaskStatus');
      cy.get('textarea', { timeout: 15000 }).should('be.visible');
    });
  });
});
