FROM python:latest

ENV PYTHONUNBUFFERED 1

WORKDIR /app

COPY ../requirements.txt /app

RUN pip install -r requirements.txt

EXPOSE 5000

CMD ["gunicorn", "--bind", "0.0.0.0:5000", "--workers", "4", "--timeout", "120", "app:app"]