FROM python:latest

ENV PYTHONUNBUFFERED 1

WORKDIR /app

COPY ../requirements.txt /app

RUN pip install -r requirements.txt

RUN adduser --disabled-password --gecos '' celeryuser

USER celeryuser

CMD ["celery", "-A", "tasks", "worker", "-l", "info", "-E"]