"""increase language column size from 4 to 20

Revision ID: a3cc259b2b15
Revises: 708dcbccc726
Create Date: 2026-03-24 15:56:35.845442

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a3cc259b2b15'
down_revision = '708dcbccc726'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('pref_language',
               existing_type=mysql.VARCHAR(length=4),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('user_language',
               existing_type=mysql.VARCHAR(length=4),
               type_=sa.String(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('user_language',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=4),
               existing_nullable=True)
        batch_op.alter_column('pref_language',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=4),
               existing_nullable=True)

    # ### end Alembic commands ###
