"""empty message

Revision ID: a5509aa15c77
Revises: 
Create Date: 2024-10-29 23:14:16.856251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5509aa15c77'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('pref_project', sa.String(length=15), nullable=True),
    sa.Column('pref_language', sa.String(length=4), nullable=True),
    sa.Column('user_language', sa.String(length=4), nullable=True),
    sa.Column('site_language', sa.String(length=4), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
