const project = {
  wikipedia: [
    "ab", "ace", "ady", "af", "alt", "am", "ami", "an", "ang", "ann", "anp",
    "ar", "arc", "ary", "arz", "as", "ast", "atj", "av", "avk", "awa", "ay",
    "az", "azb", "ba", "ban", "bar", "bbc", "bcl", "bdr", "be", "be-tarask",
    "bew", "bg", "bho", "bi", "bjn", "blk", "bm", "bn", "bo", "bpy", "br",
    "bs", "btm", "bug", "bxr", "ca", "cbk", "cdo", "ce", "ceb", "ch", "chr",
    "chy", "ckb", "co", "cr", "crh", "cs", "csb", "cu", "cv", "cy", "da",
    "dag", "de", "dga", "din", "diq", "dsb", "dtp", "dty", "dv", "dz", "ee",
    "el", "egl", "en", "eo", "es", "et", "eu", "ext", "fa", "fat", "ff", "fi",
    "fj", "fo", "fon", "fr", "frp", "frr", "fur", "fy", "ga", "gag", "gan",
    "gcr", "gd", "gl", "glk", "gn", "gom", "gor", "got", "gpe", "gsw", "gu",
    "guc", "gur", "guw", "gv", "ha", "hak", "haw", "he", "hi", "hif", "hr",
    "hsb", "ht", "hu", "hy", "hyw", "ia", "iba", "id", "ie", "ig", "igl",
    "ik", "ilo", "inh", "io", "is", "it", "iu", "ja", "jam", "jbo", "jv",
    "ka", "kaa", "kab", "kbd", "kbp", "kcg", "kg", "kge", "ki", "kk", "kl",
    "km", "kn", "ko", "koi", "krc", "ks", "ksh", "ku", "kus", "kv", "kw",
    "ky", "la", "lad", "lb", "lbe", "lez", "lfn", "lg", "li", "lij", "lld",
    "lmo", "ln", "lo", "lt", "ltg", "lv", "lzh", "mad", "mai", "jv-x-bms",
    "mdf", "mg", "mhr", "mi", "min", "mk", "ml", "mn", "mni", "mnw", "mos",
    "mr", "mrj", "ms", "mt", "mwl", "my", "myv", "mzn", "nah", "nan", "nap",
    "nds", "nds-NL", "ne", "new", "nia", "nl", "nn", "nb", "nov", "nqo",
    "nr", "nrf", "nso", "nv", "ny", "oc", "olo", "om", "or", "os", "pa",
    "pag", "pam", "pap", "pcd", "pcm", "pdc", "pfl", "pi", "pih", "pl",
    "pms", "pnb", "pnt", "ps", "pt", "pwn", "qu", "rm", "rmy", "rn", "ro",
    "nap-x-tara", "rsk", "ru", "rue", "rup", "rw", "sa", "sah", "sat", "sc",
    "scn", "sco", "sd", "se", "sg", "sgs", "sh", "shi", "shn", "si", "en",
    "sk", "skr", "sl", "sm", "smn", "sn", "so", "sq", "sr", "srn", "ss",
    "st", "stq", "su", "sv", "sw", "szl", "szy", "ta", "tay", "tcy", "tdd",
    "te", "tet", "tg", "th", "ti", "tk", "tl", "tly", "tn", "to", "tpi",
    "tr", "trv", "ts", "tt", "tum", "tw", "ty", "tyv", "udm", "ug", "uk",
    "ur", "uz", "ve", "vec", "vep", "vi", "vls", "vo", "vro", "wa", "war",
    "wo", "wuu", "xal", "xh", "xmf", "yi", "yo", "yue", "za", "zea", "zgh",
    "zh", "zu", "test",
  ],
  wikimedia: [ "commons", "meta" ],
  wiktionary: [
    "af", "am", "an", "ang", "ar", "ast", "ay", "az", "bcl", "be", "bg", "bjn",
    "blk", "bn", "br", "bs", "btm", "ca", "chr", "ckb", "co", "cs", "csb",
    "cy", "da", "de", "diq", "dv", "el", "en", "eo", "es", "et", "eu", "fa",
    "fi", "fj", "fo", "fr", "fy", "ga", "gd", "gl", "gn", "gom", "gor", "gu",
    "guw", "gv", "ha", "he", "hi", "hif", "hr", "hsb", "hu", "hy", "ia", "id",
    "ie", "ig", "io", "is", "it", "iu", "ja", "jbo", "jv", "ka", "kaa", "kbd",
    "kcg", "kk", "kl", "km", "kn", "ko", "ks", "ku", "kw", "ky", "la", "lb",
    "li", "lmo", "ln", "lo", "lt", "lv", "mad", "mg", "mi", "min", "mk", "ml",
    "mn", "mni", "mnw", "mr", "ms", "mt", "my", "na", "nah", "nan", "nds",
    "ne", "nia", "nl", "nn", "nb", "oc", "om", "or", "pa", "pl", "pnb", "ps",
    "pt", "qu", "ro", "ru", "rup", "rw", "sa", "scn", "sd", "sg", "sh", "shn",
    "shy-Latn", "si", "en", "sk", "skr", "sl", "sm", "so", "sq", "sr", "ss",
    "st", "su", "sv", "sw", "ta", "tcy", "te", "tg", "th", "ti", "tk", "tl",
    "tn", "tpi", "tr", "ts", "tt", "ug", "uk", "ur", "uz", "vec", "vi", "vo",
    "wa", "wo", "yi", "yue", "zh", "zu",
  ],
  wikibooks: [
    "af", "ar", "az", "ba", "be", "bg", "bn", "bs", "ca", "cs", "cv", "cy",
    "da", "de", "el", "en", "eo", "es", "et", "eu", "fa", "fi", "fr", "fy",
    "gl", "he", "hi", "hr", "hu", "hy", "ia", "id", "is", "it", "ja", "ka",
    "kk", "km", "ko", "ku", "ky", "la", "li", "lt", "mg", "mk", "ml", "mr",
    "ms", "ne", "nl", "nb", "oc", "pa", "pl", "pt", "ro", "ru", "sa", "shn",
    "si", "sk", "sl", "sq", "sr", "sv", "ta", "te", "tg", "th", "tl", "tr",
    "tt", "uk", "ur", "vi", "zh",
  ],
  wikiquote: [
    "af", "ar", "as", "az", "bcl", "be", "bg", "bjn", "bn", "br", "bs", "ca",
    "cs", "cy", "da", "de", "el", "en", "eo", "es", "et", "eu", "fa", "fi",
    "fr", "gl", "gor", "gu", "guw", "he", "hi", "hr", "hu", "hy", "id", "ig",
    "is", "it", "ja", "ka", "kn", "ko", "ku", "ky", "la", "li", "lt", "ml",
    "mr", "nl", "nn", "nb", "pl", "pt", "ro", "ru", "sa", "sah", "sk", "sl",
    "sq", "sr", "su", "sv", "ta", "te", "th", "tl", "tr", "uk", "ur", "uz",
    "vi", "zh",
  ],
  wikinews: [
    "ar", "bs", "ca", "cs", "de", "el", "en", "eo", "es", "fa", "fi", "fr",
    "guw", "he", "it", "ja", "ko", "li", "nl", "nb", "pl", "pt", "ro", "ru",
    "shn", "sq", "sr", "sv", "ta", "uk", "zh",
  ],
  wikisource: [
    "ar", "as", "az", "ban", "bcl", "be", "bg", "bn", "br", "bs", "ca", "cs",
    "cy", "da", "de", "el", "en", "eo", "es", "et", "eu", "fa", "fi", "fo",
    "fr", "gl", "gu", "he", "hi", "hr", "hu", "hy", "id", "is", "it", "ja",
    "jv", "ka", "kn", "ko", "la", "li", "lij", "lt", "mk", "ml", "mr", "ms",
    "my", "nan", "nap", "nl", "nb", "or", "pa", "pl", "pms", "pt", "ro", "ru",
    "sa", "sah", "sk", "sl", "sr", "su", "sv", "ta", "tcy", "te", "th", "tr",
    "uk", "vec", "vi", "wa", "yi", "zh",
  ],
  wikiversity: [
    "ar", "cs", "de", "el", "en", "es", "fi", "fr", "hi", "it", "ja", "ko",
    "pt", "ru", "sl", "sv", "zh",
  ],
  wikivoyage: [
    "bn", "cs", "de", "el", "en", "eo", "es", "fa", "fi", "fr", "he", "hi",
    "it", "ja", "nl", "pl", "ps", "pt", "ro", "ru", "shn", "sv", "tr", "uk",
    "vi", "zh",
  ],
};

export default project;
