name: Cypress Tests

on:
  push:
    branches: master
  pull_request:
    branches: master
  workflow_dispatch: 

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code 🛎
        uses: actions/checkout@v4

      - name: Setup Node.js 🖨️
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run Cypress Tests 🧪
        uses: cypress-io/github-action@v6
        with:
          working-directory: frontend
          
          start: npm start
          
          wait-on: 'http://localhost:3000'
          
          wait-on-timeout: 120